sudo: false
language: go

services:
    - docker

env:
    global:
        - REDIS_VERSION=alpine

go:
    - 1.7
    - tip

before_install:
    - docker run -d -p 27017:27017 "redis:$REDIS_VERSION"

install:
    - "github.com/stretchr/testify/assert"

script: go test -coverprofile=c.out $(go list ./... | grep -v /vendor/)

after_success: go tool cover -func=c.out
