sudo: false
language: go

services:
    - docker

env:
    global:
        - REDIS_VERSION=alpine

go:
    - 1.7
    - tip

before_install:
    - docker run -d -p 27017:27017 "redis:$REDIS_VERSION"

install:
    - go get github.com/stretchr/testify/assert

script:
    - go test -race -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /vendor/)

after_success:
    - go tool cover -func=coverage.txt
    - bash <(curl -s https://codecov.io/bash)
